
- name: gather facts
  hosts: LB, my_web_servers
  gather_facts: yes
  tasks: []

- name: Configuring httpd server on backend server
  hosts: my_web_servers 
  gather_facts: no
  roles:
          - myapache

- name: Configuring HAProxy
  hosts: LB
  gather_facts: no
  roles:
          - myloadbalancer


